before_script:
- apt-get update -qq
- apt-get install -y -qq doxygen fonts-freefont-ttf graphviz

pages:
  script:
  - python3 docs/dox_examples.py
  - doxygen docs/Doxyfile
  - mv docs/html public
  artifacts:
    paths:
    - public
  only:
  - master

