default:
    image: ubuntu:latest
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq doxygen fonts-freefont-ttf graphviz python3-pip make python3-opencv libagg-dev fonts-ubuntu zip git m4
        - pip3 install coverage Pillow numpy scipy cairosvg fonttools grapheme

variables:
    DEBIAN_FRONTEND: noninteractive

stages:
    - test
    - build

pages:
    stage: build
    script:
        - git clone https://github.com/twitter/twemoji.git
        - make -B docs -j 4
        - mv docs/html public
    after_script:
        - mv htmlcov public/coverage
    artifacts:
        paths:
            - public
    only:
        - master
    dependencies:
        - test

test:
    stage: test
    script:
        - ./test.sh
    artifacts:
        paths:
            - htmlcov/
        when: always

build:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - dist/*
    dependencies:
        - test

# https://gitlab.com/mattia.basaglia/tgs/-/ci/lint
