stages:
    - test
    - pages

pages:
    stage: pages
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq doxygen fonts-freefont-ttf graphviz
    script:
        - python3 docs/dox_examples.py
        - python3 docs/dox_lottie.py
        - doxygen docs/Doxyfile
        - mv docs/html public
    after_script:
        - mv htmlcov public/coverage
    artifacts:
        paths:
            - public
    only:
        - master
    dependencies:
        - test

test:
    stage: test
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq python3-pip
        - pip install coverage
    script:
        - ./test.sh
    artifacts:
        paths:
            - htmlcov/
        when: always

# https://gitlab.com/mattia.basaglia/tgs/-/ci/lint
