stages:
    - test
    - pages

pages:
    stage: pages
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq doxygen fonts-freefont-ttf graphviz python3-pip make python3-opencv libagg-dev
        - pip3 install Pillow numpy scipy cairosvg git+https://github.com/flupke/pypotrace.git@py3k
    script:
        - make -B docs -j 4
        - mv docs/html public
    after_script:
        - mv htmlcov public/coverage
    artifacts:
        paths:
            - public
    only:
        - master
    dependencies:
        - test

test:
    stage: test
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq python3-pip python3-opencv libagg-dev
        - pip3 install coverage Pillow numpy scipy cairosvg git+https://github.com/flupke/pypotrace.git@py3k
    script:
        - ./test.sh
    artifacts:
        paths:
            - htmlcov/
        when: always

# https://gitlab.com/mattia.basaglia/tgs/-/ci/lint
